/**
 * OAuth Configuration Constants
 * 
 * CRITICAL: These values must match across:
 * 1. Supabase Dashboard (auto-generated)
 * 2. Google Cloud Console (manually configured)
 * 3. This file (reference/documentation)
 * 
 * DO NOT CHANGE unless migrating to a new Supabase project
 */

// Supabase OAuth Callback URI (auto-generated by Supabase)
// This URL is handled by Supabase Auth and should NEVER be changed
export const SUPABASE_OAUTH_CALLBACK_URI = 'https://cpmjtrrbzupvgqcapxak.supabase.co/auth/v1/callback';

// Application redirect URLs after successful OAuth
// These can be customized per environment
export const OAUTH_REDIRECT_URLS = {
  development: {
    default: '/dashboard',
    afterLogin: '/dashboard',
    afterSignup: '/dashboard',
  },
  production: {
    default: '/dashboard',
    afterLogin: '/dashboard',
    afterSignup: '/dashboard',
  },
};

// Google Cloud Console Configuration Reference
export const GOOGLE_CLOUD_CONSOLE = {
  credentialsUrl: 'https://console.cloud.google.com/apis/credentials',
  consentScreenUrl: 'https://console.cloud.google.com/apis/credentials/consent',
  
  // Required settings in Google Cloud Console:
  requiredRedirectUris: [
    SUPABASE_OAUTH_CALLBACK_URI, // REQUIRED - Supabase handles OAuth callback
  ],
  
  optionalRedirectUris: [
    'http://localhost:5173/dashboard', // Optional - for local testing
  ],
  
  requiredJavaScriptOrigins: [
    'http://localhost:5173', // Development
    // Add production domain here: 'https://yourdomain.com'
  ],
};

// OAuth Provider Settings
export const OAUTH_PROVIDERS = {
  google: {
    provider: 'google',
    scopes: ['email', 'profile', 'openid'], // Default scopes
    queryParams: {
      access_type: 'offline',
      prompt: 'select_account consent', // Force account selection
    },
  },
};

// Verification Helper
export function verifyOAuthConfig() {
  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
  const expectedUrl = 'https://cpmjtrrbzupvgqcapxak.supabase.co';
  
  if (supabaseUrl !== expectedUrl) {
    console.error('❌ OAuth Configuration Error:');
    console.error(`   Supabase URL mismatch!`);
    console.error(`   Expected: ${expectedUrl}`);
    console.error(`   Got: ${supabaseUrl}`);
    console.error(`   → Update .env file with correct VITE_SUPABASE_URL`);
    return false;
  }
  
  console.log('✅ OAuth Configuration: Correct');
  console.log(`   Callback URI: ${SUPABASE_OAUTH_CALLBACK_URI}`);
  return true;
}

/**
 * Get OAuth redirect URL for current environment
 * @param {string} path - Path to redirect to after OAuth (default: '/dashboard')
 * @returns {string} Full redirect URL
 */
export function getOAuthRedirectUrl(path = null) {
  const isDevelopment = import.meta.env.DEV;
  const env = isDevelopment ? 'development' : 'production';
  const defaultPath = path || OAUTH_REDIRECT_URLS[env].default;
  
  return `${window.location.origin}${defaultPath}`;
}

// Export Supabase project info for reference
export const SUPABASE_PROJECT = {
  projectId: 'cpmjtrrbzupvgqcapxak',
  projectUrl: 'https://cpmjtrrbzupvgqcapxak.supabase.co',
  authCallbackUrl: SUPABASE_OAUTH_CALLBACK_URI,
  dashboardUrl: 'https://supabase.com/dashboard/project/cpmjtrrbzupvgqcapxak',
};

